# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18270c09abd901fb9a08f9c15de1577f0b9df3879f0a58ba030187097d752e4c74668d9d1ff13fad01d6d679a97daf03a237de72ee64a2e03a076e3af2d72b7f

test:
  secret_key_base: 2a9bc7aa31be030443fadb78b2f29bf178f537cfc7c5bf137f8c46b7a98945c89d65698f4bc76dda673dc63f4527aff7ff47e0ece05980cbbe95df5a659cca34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
